### PR TITLE
Update to Gradle 7.6.3

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by jeremylong** [comment]
Its not that I don't trust people - but until I add something like [gradle-wrapper-validation](https://github.com/marketplace/actions/gradle-wrapper-validation) I do not plan on merging any PRs upgrading binary executables...

**Comment by larsgrefer** [comment]
@jeremylong I've opened #360 to add the validation action

**Comment by jeremylong** [comment]
Mind rebasing this PR to add the validation to this run?

**Comment by larsgrefer** [comment]
done

**Review by jeremylong — APPROVED** [review]

**Pull request merged**
