### PR TITLE
Allow to use Action for configuration in extensions to better support non-Groovy consumers (#187)

### LINKED ISSUE #187: Allow passing Action<T> when configuring nested extensions
If you're using configuring the plugin using Java code, you really want to write things like this:

    dependencyCheck.cve(cve -> {
        cve.setUrlBase(...);
    });

But currently you can't, because the `cve` method only takes `Closure`, making it only callable from Groovy.

All methods to configure extensions should have overloads taking `Action<T>`. This might affect Kotlin build scripts too but I haven't found out yet because other things break those anyway.

### PR DESCRIPTION
**Pull request by Vampire**
fixes #187

### CODE REVIEW

**Review by jeremylong — APPROVED** [review]
LGTM

**Comment by jeremylong** [comment]
Thanks!

**Comment by chadlwilson** [comment]
How are users expected to use the Action variants in Groovy to avoid the deprecations?

Was it necessary to deprecate all the closure variants here?

**Comment by Vampire** [comment]
Without deprecation it is hard to later remove them.
And in non-dynamic languages or if the Groovy files are statically compiled, you would otherwise get trouble when later removing the `Closure` variants as the already compiled code would not just "switch over" like the dynamic Groovy code would do.

In Groovy you have the two possibilities to either ignore the deprecation warning, or explicitly using the `Action` variant.

Or you switch over to Kotlin DSL instead. By now it is the default DSL, you immediately get type-safe build scripts, actually helpful error messages if you mess up the syntax, and amazingly better IDE support when using a good IDE like IntelliJ IDEA or Android Studio. :-)

**Comment by chadlwilson** [comment]
I understand that re kotlin, but some of us have massive multi project Gradle builds and moving to kotlin is significant effort better spent elsewhere.

The question is around how to even use the action variant within groovy (the syntax). If there is no canonical (non clunky) way to do so, and if we are not deprecating support for groovy entirely, they probably shouldn't be marked as deprecated. Training folks to ignore deprecation warnings is not helpful.

Currently the documentation doesn't show folks how to use a non-deprecated approach.

**Comment by jeremylong** [comment]
Wouldn't it just be:

```
dependencyCheck {
    data.directory='d:/nvd'
    analyzers.assemblyEnabled=false
}
```

Basically just replace the `{}` with dot walking.

**Comment by Vampire** [comment]
Well, this plugin's documentation should imho not be a Groovy language documentation, that is up to Groovy. ;-)
It is for example
```groovy
dependencyCheck {
   proxy({
      it.port = 0
   } as Action)
}
```

Or you use neither by doing
```groovy
dependencyCheck {
   proxy.port = 0
}
```

Besidest that, even with
```groovy
dependencyCheck {
   proxy {
      port = 0
   }
}
```
Gradle does not complain with a deprecation warning for me.

**Comment by jeremylong** [comment]
I really should update the docs to be kotlin at some point...

**Comment by chadlwilson** [comment]
Ahh thanks, despite many years of using Gradle it wasn't obvious to me that moving to dot syntax is what it takes to move to using the actions overloads. I guess this is the difference from the perspective of users vs Gradle plugin authors; as the closure syntax is the canonical way in Gradle-groovy to group related configration in its DSL.

> Besidest that, even with
> 
> ```groovy
> dependencyCheck {
>    proxy {
>       port = 0
>    }
> }
> ```

Gradle doesn't complain, but IntelliJ IDEA (correctly) does, as this is passing a closure.

image

**Comment by Vampire** [comment]
> it wasn't obvious to me that moving to dot syntax is what it takes to move to using the actions overloads.

That would be quite strange and is not what is happening as I said above.
It is another way of doing the configuration which you can use almost anywhere in Gradle.
The "scoped" / "grouped" way ist just more often used as it looks nicer usually.
In some cases the "grouped" way is different, for example as it might be evaluated lazily while dotted syntax is eager,
especially without `Property`s being used, but here this is not the case, as the methods would also right away evaluate the given "group".

**Comment by chadlwilson** [comment]
> > it wasn't obvious to me that moving to dot syntax is what it takes to move to using the actions overloads.
> 
> That would be quite strange and is not what is happening as I said above. It is another way of doing the configuration which you can use almost anywhere in Gradle.

OK, maybe better to ignore whether it is "actions syntax" or "neither" from my comment - I'm probably better to have written it as "to move to using a non-deprecated approach". I don't actually know how Gradle DSL magic translates these syntaxes internally to bind to the overloads/extension config classes, especially when using `@CompileStatic` (and shouldn't really have to, as a user).

**Pull request merged**
